routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UrlController as AdminUrlController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UrlController;
use Illuminate\Support\Facades\Route;

Route::get('/', [UrlController::class, 'index'])->name('url.index');

Route::get('/installstorage', function() {
    Artisan::call('storage:link');
    return redirect('/login');
});

Route::get('administration/dashboard', [DashboardController::class, '__invoke'])->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('administration/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('administration/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('administration/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

});

Route::prefix('administration')->name('administration.')->middleware('auth')->group(function () {
    Route::resource('links', AdminUrlController::class)->parameters(['links' => 'url']);
    Route::get('download/qrcode/{url}', [AdminUrlController::class, 'downloadQrCode'])->name('links.download');
    Route::resource('users', App\Http\Controllers\Admin\UserController::class)->except('show');
});

require __DIR__ . '/auth.php';

Route::get('{slug}', [UrlController::class, 'redirection'])->name('url.redirection');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

/**
 * @mixin IdeHelperUser
 */
class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'surname',
        'email',
        'password',
    ];

    protected $guarded = [];

    public function urls()
    {
        return $this->hasMany(Url::class);
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    protected $appends = ['created_at_formatted'];

    public function getCreatedAtFormattedAttribute()
    {
        $createdAt = $this->attributes['created_at'];

        // Vérifier si la valeur de created_at est déjà un objet Carbon
        if ($createdAt instanceof Carbon) {
            return $createdAt->locale('fr')->isoFormat('LLLL');
        }

        // Si ce n'est pas un objet Carbon, essayez de le parser
        if (is_string($createdAt)) {
            return Carbon::parse($createdAt)->locale('fr')->isoFormat('LLLL');
        }

        // Si la valeur n'est ni un objet Carbon ni une chaîne de caractères valide, retournez null ou une valeur par défaut
        return null; // ou une valeur par défaut, selon le cas
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProfileUpdateRequest;
use App\Models\User;
use Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProfileUpdateRequest $request)
    {

        $validatedData = $request->validated();
        $validatedData['password'] = Hash::make('admin');
        $user = User::create($validatedData);

        return redirect()->route('administration.users.index')->with('status', 'users-created');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ProfileUpdateRequest $request, User $user)
    {
        $user->update($request->validated());

        return redirect()->route('administration.users.index')->with('status', 'users-updated');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/users/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="bg-white p-4 flex items-center flex-wrap">
            <ul class="flex items-center">
                <li class="inline-flex items-center">
                <span class="text-gray-600 hover:text-blue-500">Fil d'ariane : </span>
                <a href="{{ route('dashboard') }}" class="text-gray-600 hover:text-blue-500">
                    <svg class="w-5 h-auto fill-current mx-2 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M10 19v-5h4v5c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-7h1.7c.46 0 .68-.57.33-.87L12.67 3.6c-.38-.34-.96-.34-1.34 0l-8.36 7.53c-.34.3-.13.87.33.87H5v7c0 .55.45 1 1 1h3c.55 0 1-.45 1-1z"/></svg>
                </a>
                <a href="{{ route('dashboard') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Tableau de bord') }}
                </a>

                <span class="mx-4 h-auto text-gray-400 font-medium ml-2 mr-2">/</span>
                </li>

                <li class="inline-flex items-center">
                <a href="{{ route('administration.users.index') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Listing des utilisateurs') }}
                </a>
                <span class="mx-4 h-auto text-gray-400 font-medium ml-2 mr-2">/</span>
                </li>
                <li class="inline-flex items-center">
                <a href="{{ route('administration.users.create') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Ajouter un nouvel utilisateur') }}
                </a>

                </li>
            </ul>
        </div>
    </x-slot>
    <div class="py-2 bg-white">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                     <form id="send-verification" method="post" action="{{ route('administration.users.store') }}">
                            @csrf
                        @include('admin.users.partials.forms')
                        <div class="flex justify-center items-center gap-4">
                            <x-primary-button>{{ __('Ajouter ce nouvel utilisateur') }}</x-primary-button>
                                @if (session('status') === 'profile-updated')
                                    <p
                                        x-data="{ show: true }"
                                        x-show="show"
                                        x-transition
                                        x-init="setTimeout(() => show = false, 2000)"
                                        class="text-sm text-gray-600"
                                    >{{ __('Demande prise en compte.') }}</p>
                                @endif
                        </div>
                     </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="bg-white p-4 flex items-center flex-wrap">
            <ul class="flex items-center">
                <li class="inline-flex items-center">
                <span class="text-gray-600 hover:text-blue-500">Fil d'ariane : </span>
                <a href="{{ route('dashboard') }}" class="text-gray-600 hover:text-blue-500">
                    <svg class="w-5 h-auto fill-current mx-2 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M10 19v-5h4v5c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-7h1.7c.46 0 .68-.57.33-.87L12.67 3.6c-.38-.34-.96-.34-1.34 0l-8.36 7.53c-.34.3-.13.87.33.87H5v7c0 .55.45 1 1 1h3c.55 0 1-.45 1-1z"/></svg>
                </a>
                <a href="{{ route('dashboard') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Tableau de bord') }}
                </a>

                <span class="mx-4 h-auto text-gray-400 font-medium ml-2 mr-2">/</span>
                </li>

                <li class="inline-flex items-center">
                <a href="{{ route('administration.users.index') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Listing des utilisateurs') }}
                </a>
                <span class="mx-4 h-auto text-gray-400 font-medium ml-2 mr-2">/</span>
                </li>
                <li class="inline-flex items-center">
                <a href="{{ route('administration.users.edit', $user) }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Modifier un utilisateur') }}
                </a>

                </li>
            </ul>
        </div>
    </x-slot>

    <div class="py-12 bg-white">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    <section>
                        <form id="send-verification" method="post" action="{{ route('administration.users.update', $user) }}">
                            @method('PATCH')
                            @csrf
                            @include('admin.users.partials.forms')
                            <div class="flex justify-center items-center gap-4">
                                <x-primary-button>{{ __('Modifier cet utilisateur') }}</x-primary-button>
                                @if (session('status') === 'user-updated')
                                    <p
                                        x-data="{ show: true }"
                                        x-show="show"
                                        x-transition
                                        x-init="setTimeout(() => show = false, 5000)"
                                        class="text-sm text-gray-600"
                                    >{{ __('Modification prise en compte.') }}
                                    </p>
                                @endif
                            </div>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="bg-white p-4 flex items-center flex-wrap">
            <ul class="flex items-center">
                <li class="inline-flex items-center">
                <span class="text-gray-600 hover:text-blue-500">Fil d'ariane : </span>
                <a href="{{ route('dashboard') }}" class="text-gray-600 hover:text-blue-500">
                    <svg class="w-5 h-auto fill-current mx-2 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M10 19v-5h4v5c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-7h1.7c.46 0 .68-.57.33-.87L12.67 3.6c-.38-.34-.96-.34-1.34 0l-8.36 7.53c-.34.3-.13.87.33.87H5v7c0 .55.45 1 1 1h3c.55 0 1-.45 1-1z"/></svg>
                </a>
                <a href="{{ route('dashboard') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Tableau de bord') }}
                </a>

                <span class="mx-4 h-auto text-gray-400 font-medium ml-2 mr-2">/</span>
                </li>

                <li class="inline-flex items-center">
                <a href="{{ route('administration.users.index') }}" class="text-gray-600 hover:text-blue-500">
                    {{ __('Listing des utilisateurs') }}
                </a>

                </li>
            </ul>
        </div>
    </x-slot>
    <div class="py-2 bg-white">
        <div class="flex items-center">
            <a href="{{ route('administration.users.create') }}" class="bg-green-200 rounded-lg font-normal text-gray-900 pl-4 pr-4 pt-1 pb-1 mx-auto">{{ __('Création d\'un nouvel utilisateur') }}</a>
        </div>
    </div>
    <div class="py-2 bg-white">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    @include('admin.users.partials.notifications')
                    <table class="min-w-full text-left text-sm font-light text-surface dark:text-white">
                        <thead class="border-b border-r border-l border-t border-neutral-200 font-medium dark:border-white/10">
                            <tr>
                                <th class="w-1/3 border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">Nom</th>
                                <th class="w-1/3 border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">Prénom</th>
                                <th class="w-1/4 border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">Inscrit depuis le</th>
                                <th class="w-auto text-center border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">Action</th>
                            </tr>
                        </thead>
                        @foreach($users as $user)
                            <tbody>
                                <tr class="border-l border-r border-b border-t border-neutral-200 dark:border-white/10">
                                    <td class="border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">{{ $user->name }}</td>
                                    <td class="border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">{{ $user->surname }}</td>
                                    <td class="border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">{{ $user->created_at_formatted }}</td>
                                    <td class="border-e border-r border-b border-neutral-200 px-6 py-4 dark:border-white/10">
                                        <div class="flex items-center">
                                            <a href="{{ route('administration.users.edit', $user) }}" class="ml-1 mr-1 transform transition duration-300 hover:scale-150 inline-block">
                                                <x-icon-edit class="w-8 h-8"/>
                                            </a>
                                            <form id="deleteForm_{{ $user['id'] }}" action="{{ route('administration.users.destroy', $user) }}" method="post" class="inline-block">
                                                @csrf
                                                @method('delete')
                                                <button onclick="return confirmUserDelete({{ $user['id'] }})" class="ml-1 mr-1 transform transition duration-300 hover:scale-150"><x-icon-delete class="w-8 h-8"/></button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        @endforeach
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>